# Generated by Django 6.0.1 on 2026-01-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0002_alter_request_options_request_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='channel',
        ),
        migrations.AddField(
            model_name='webinar',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
